version: "3.3"

services:
  nuxt-app:
    build: .
    container_name: dapp.polarnodes
    restart: always
    ports:
      - "7000:7000"
    command: "npm run start"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
